### ISSUE TITLE
Esp8266 not starting automatically after user entering correct password

### ISSUE THREAD

**Issue by itzpa1** [p3tr0s/PhiSiFi#4]
Esp8266 not starting automatically after user entering correct password. And when I reconnect esp8266 to power . It's not showing password.. even the default AP' name is different like 'Fairy.......'

**Comment by p3tr0s** [comment]
In order to check the password the arduino device used has to be able to connect to the original AP. 
So you need reliable singal. If the device connects to the original AP with the password you gave it it will restart with the original AP name, you will have to connect back to it, and on the bottom it will give you the AP name and Password.
Do not hard reset or this info will be lost.
About the AP name - probably the device you use has become sentient and is able to rewrite its code.
